/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author shubh
 */
public class CreditCardScreen extends javax.swing.JFrame {

    /**
     * Creates new form CreditCardScreen
     */
    private static String lang;
    private static RegisteredUser r;
    public CreditCardScreen(String lang, RegisteredUser r) {
        CreditCardScreen.r = r;
        CreditCardScreen.lang = lang;
        initComponents();
        setSize(1024, 803);
        getContentPane().setBackground(Color.WHITE);
        jLabel2.setText("fr".equals(lang)?"Informations sur la carte de crédit":"Credit Card Information");
        jLabel3.setText("fr".equals(lang)?"Nom":"Name");
        jLabel4.setText("fr".equals(lang)?"Numéro de carte":"Card Number");
        jLabel5.setText("fr".equals(lang)?"Date d'expiration (JJ/AAAA)":"Expiration Date(DD/YYYY)");
        jLabel6.setText("fr".equals(lang)?"CVV":"CVV");
        jButton1.setText("fr".equals(lang)?"VÉRIFIER":"VERIFY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/New Project (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 768);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(133, 220, 186));
        jLabel2.setText("Credit Card Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 220, 690, 70);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 220, 186));
        jLabel3.setText("Exipiration Date(DD/YYYY)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 440, 480, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(133, 220, 186));
        jLabel4.setText("CVV Code");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 500, 480, 48);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(133, 220, 186));
        jLabel5.setText("Card Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 380, 480, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(133, 220, 186));
        jLabel6.setText("Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 320, 480, 50);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextArea1.setRows(1);
        jTextArea1.setTabSize(1);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 500, 234, 50);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(1);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextArea2.setRows(1);
        jTextArea2.setTabSize(1);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(600, 320, 234, 50);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setColumns(1);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextArea3.setRows(1);
        jTextArea3.setTabSize(1);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(600, 380, 234, 50);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setColumns(1);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextArea4.setRows(1);
        jTextArea4.setTabSize(1);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(600, 440, 234, 50);

        jButton1.setBackground(new java.awt.Color(133, 220, 186));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VERIFY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 570, 240, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                System.out.println("print");
                jButton1.setEnabled(false);
                // create a new JDialog to show the loading animation
                JDialog loadingDialog = new JDialog();
                loadingDialog.setSize(300, 100);
                Color bgColor = new Color(0x85DCBA);
                loadingDialog.setUndecorated(true);

                // create a JLabel to show the loading animation
                JLabel loadingLabel = new JLabel("Loading");
                loadingLabel.setBackground(bgColor);
                loadingLabel.setForeground(Color.WHITE);
                
                loadingLabel.setOpaque(true);
                loadingLabel.setFont(new Font("Arial", Font.BOLD, 60));
                loadingDialog.add(loadingLabel);
                
                // Get the dimensions of the screen
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

// Get the dimensions of the dialog
Dimension dialogSize = loadingDialog.getSize();

// Calculate the x and y coordinates of the top-left corner of the dialog
int x = (screenSize.width - dialogSize.width) / 3;
int y = (screenSize.height - dialogSize.height) / 2;

// Set the location of the dialog
loadingDialog.setLocation(x, y);


                // create a Timer to update the loading animation
                Timer timer = new Timer(500, new ActionListener() {
                    int count = 0;
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        count++;
                        if (count > 3) {
                            count = 1;
                        }
                        loadingLabel.setText("Loading" + ".".repeat(count));
                    }
                });

                // start the timer to update the loading animation
                timer.start();

                // center the loading dialog on the screen
//                loadingDialog.setLocationRelativeTo(null);
                loadingDialog.setVisible(true);

                // create a Timer to remove the loading dialog after 5 seconds
                Timer timer2 = new Timer(5000, (ActionEvent e) -> {
                    loadingDialog.dispose();
                    JOptionPane.showMessageDialog(this, "fr".equals(lang) ? "Vérifié" : "Verified");
                RegisteredUserMenu m=new RegisteredUserMenu(lang,r);
                m.show();
                dispose();
                    jButton1.setEnabled(true); // enable the submit button
                    ((Timer)e.getSource()).stop();
                });

                // start the timer to remove the loading dialog
                timer2.start();
                //implementation to add plan in history of user
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreditCardScreen(lang,r).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
