/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;


import java.awt.Color;
import static javaapplication2.ReloadIGoMenu.userTmp;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rahul
 */
public class PurchaseTicket extends JFrame  {

    /**
     * Creates new form PurchaseTicket
     */
    private static String lang;
    public static RegisteredUser userTmp;
    public PurchaseTicket(String lang,RegisteredUser R) {
        userTmp=R;
        initComponents();
        setSize(1024, 803);
        getContentPane().setBackground(Color.WHITE);
         PurchaseTicket.lang = lang;
        singletrip.setText("fr".equals(lang)?"Single voyage-$3.5":"Single Trip-$3.5");
        doubletrip.setText("fr".equals(lang)?"Double voyage-$6.5":"Double Trip-$6.5");
        singleday.setText("fr".equals(lang)?"seule journée-$13":"Single Day-$13");
        cash.setText("fr".equals(lang)?"Espèces":"Cash");
        card.setText("fr".equals(lang)?"Carte":"Card");
        payvia.setText("fr".equals(lang)?"Payer via":"Pay Via");
        jButton1.setText("fr".equals(lang)?"Retourner":"Go Back");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        singletrip = new javax.swing.JRadioButton();
        doubletrip = new javax.swing.JRadioButton();
        singleday = new javax.swing.JRadioButton();
        payvia = new javax.swing.JLabel();
        card = new javax.swing.JButton();
        cash = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        singletrip.setBackground(new java.awt.Color(133, 220, 186));
        buttonGroup1.add(singletrip);
        singletrip.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        singletrip.setForeground(new java.awt.Color(255, 255, 255));
        singletrip.setText("Single Trip - $3.5");
        singletrip.setOpaque(true);
        getContentPane().add(singletrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 410, 70));

        doubletrip.setBackground(new java.awt.Color(133, 220, 186));
        buttonGroup1.add(doubletrip);
        doubletrip.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        doubletrip.setForeground(new java.awt.Color(242, 242, 242));
        doubletrip.setText("Double Trip - $6.5");
        doubletrip.setOpaque(true);
        doubletrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubletripActionPerformed(evt);
            }
        });
        getContentPane().add(doubletrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 410, 60));

        singleday.setBackground(new java.awt.Color(133, 220, 186));
        buttonGroup1.add(singleday);
        singleday.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        singleday.setForeground(new java.awt.Color(242, 242, 242));
        singleday.setText("Single Day - $ 13");
        singleday.setOpaque(true);
        singleday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singledayActionPerformed(evt);
            }
        });
        getContentPane().add(singleday, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 410, 60));

        payvia.setBackground(new java.awt.Color(133, 220, 186));
        payvia.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        payvia.setForeground(new java.awt.Color(133, 220, 186));
        payvia.setText("Pay Via : ");
        getContentPane().add(payvia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 220, 60));

        card.setBackground(new java.awt.Color(133, 220, 186));
        card.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        card.setForeground(new java.awt.Color(255, 255, 255));
        card.setText("Card");
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });
        getContentPane().add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 140, 60));

        cash.setBackground(new java.awt.Color(133, 220, 186));
        cash.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        cash.setForeground(new java.awt.Color(255, 255, 255));
        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        getContentPane().add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 140, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/New Project (1) (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        jButton1.setBackground(new java.awt.Color(133, 220, 186));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doubletripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubletripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doubletripActionPerformed

    private void singledayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singledayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singledayActionPerformed

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        // TODO add your handling code here:
        String tripType=null;
        double amount=0;
        if(singleday.isSelected()){
            tripType="Single Day-Booking";
            amount=13;
        }
        if(singletrip.isSelected()){
            tripType="Single Trip-Booking";
            amount=3.5;
        }
        if(doubletrip.isSelected()){
            tripType="Double Trip-Booking";
            amount=6.5;
        }
        boolean ticketBooked;
        if(userTmp==null){
            PurchaseTicketInformation ticketInfo=new PurchaseTicketInformation("GuestUser",tripType,amount,"Card");
            ticketBooked=PurchaseTicketInformation.writeIntoPurchaseTicketDB(ticketInfo);
        }
        else{
            PurchaseTicketInformation ticketInfo=new PurchaseTicketInformation(userTmp.getEmail(),tripType,amount,"Card");
             ticketBooked=PurchaseTicketInformation.writeIntoPurchaseTicketDB(ticketInfo);
        }
        if(ticketBooked){
//            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Billet réservé avec succès":"Ticket Booked Successfully");
            singletrip.setSelected(false);
             doubletrip.setSelected(false);
              singleday.setSelected(false);
              CreditCardScreen c=new CreditCardScreen(lang, userTmp);
                c.show();
                dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Erreur : Échec":"Error: Unsuccessfull");
            singletrip.setSelected(false);
             doubletrip.setSelected(false);
              singleday.setSelected(false);
        }
        
        
    }//GEN-LAST:event_cardActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:String tripType=null;
        double amount=0;
        String tripType=null;
        if(singleday.isSelected()){
            tripType="Single Day-Booking";
            amount=13;
        }
        if(singletrip.isSelected()){
            tripType="Single Trip-Booking";
            amount=3.5;
        }
        if(doubletrip.isSelected()){
            tripType="Double Trip-Booking";
            amount=6.5;
        }
        boolean ticketBooked;
        if(userTmp==null){
            PurchaseTicketInformation ticketInfo=new PurchaseTicketInformation("GuestUser",tripType,amount,"Cash");
            ticketBooked=PurchaseTicketInformation.writeIntoPurchaseTicketDB(ticketInfo);
        }
        else{
            PurchaseTicketInformation ticketInfo=new PurchaseTicketInformation(userTmp.getEmail(),tripType,amount,"Cash");
             ticketBooked=PurchaseTicketInformation.writeIntoPurchaseTicketDB(ticketInfo);
        }
        if(ticketBooked){
//            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Billet réservé avec succès":"Ticket Booked Successfully");
            singletrip.setSelected(false);
             doubletrip.setSelected(false);
              singleday.setSelected(false);
            CashPayment c=new CashPayment(lang, userTmp);
            c.show();
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Erreur : Échec":"Error: Unsuccessfull");
            singletrip.setSelected(false);
             doubletrip.setSelected(false);
              singleday.setSelected(false);
        }
        
    }//GEN-LAST:event_cashActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(userTmp==null){
            LanguageSelection Lan=new LanguageSelection();
            Lan.show();
            dispose();
        }
        else{
            RegisteredUserMenu menu=new RegisteredUserMenu(lang,userTmp);
                menu.show();
                dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseTicket(lang,userTmp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton card;
    private javax.swing.JButton cash;
    private javax.swing.JRadioButton doubletrip;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel payvia;
    private javax.swing.JRadioButton singleday;
    public javax.swing.JRadioButton singletrip;
    // End of variables declaration//GEN-END:variables

   
}
