/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author shubh
 */
public class CashPayment extends javax.swing.JFrame {

    /**
     * Creates new form CardPayment
     */
    private static String lang,userType;
    private static RegisteredUser r;
    public CashPayment(String lang, RegisteredUser r,String userType) {
        CashPayment.userType = userType;
        CashPayment.r = r;
        CashPayment.lang = lang;
        initComponents();
        setSize(1024, 803);
        getContentPane().setBackground(Color.WHITE);
        jLabel3.setText("fr".equals(lang)?"Insérez votre argent pour le paiement...":"Insert Your Cash For Payment...");
        jButton1.setText("fr".equals(lang)?"VÉRIFIER":"VERIFY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(133, 220, 186));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton1.setText("VERIFY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 390, 260, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/New Project (1) (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1030, 768);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 220, 186));
        jLabel3.setText("Insert Your Cash For Payment...");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(158, 271, 791, 89);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("print");
                jButton1.setEnabled(false);
                // create a new JDialog to show the loading animation
                JDialog loadingDialog = new JDialog();
                loadingDialog.setSize(300, 100);
                Color bgColor = new Color(0x85DCBA);
                loadingDialog.setUndecorated(true);

                // create a JLabel to show the loading animation
                JLabel loadingLabel = new JLabel("Loading");
                loadingLabel.setBackground(bgColor);
                loadingLabel.setForeground(Color.WHITE);
                
                loadingLabel.setOpaque(true);
                loadingLabel.setFont(new Font("Arial", Font.BOLD, 60));
                loadingDialog.add(loadingLabel);
                
                // Get the dimensions of the screen
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

// Get the dimensions of the dialog
Dimension dialogSize = loadingDialog.getSize();

// Calculate the x and y coordinates of the top-left corner of the dialog
int x = (screenSize.width - dialogSize.width) / 3;
int y = (screenSize.height - dialogSize.height) / 2;

// Set the location of the dialog
loadingDialog.setLocation(x, y);


                // create a Timer to update the loading animation
                Timer timer = new Timer(500, new ActionListener() {
                    int count = 0;
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        count++;
                        if (count > 3) {
                            count = 1;
                        }
                        loadingLabel.setText("Loading" + ".".repeat(count));
                    }
                });

                // start the timer to update the loading animation
                timer.start();

                // center the loading dialog on the screen
//                loadingDialog.setLocationRelativeTo(null);
                loadingDialog.setVisible(true);
                    
                // create a Timer to remove the loading dialog after 5 seconds
                Timer timer2 = new Timer(5000, (ActionEvent e) -> {
                    loadingDialog.dispose();
                    //JOptionPane.showMessageDialog(this, "fr".equals(lang) ? "Vérifié: Achat réussi" : "Verified: Purchase Successfull")
                    //;
                    String[] options = {"Print Receipt", "Exit"}; 
                    String outputlang=null;
                    String heading=null;
                    if("fr".equals(lang)){
                        outputlang="Vérifié: Achat réussi";
                        heading="Confirmation d'achat";
      
                    }
                    else{
                        outputlang="Verified: Purchase Successfull";
                        heading="Purchase Confirmation";
                    }
                    int result = JOptionPane.showOptionDialog(
                    this,
                    outputlang, 
                    heading,            
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,     //no custom icon
                    options,  //button titles
                    options[0] //default button
            );
                    if(result == JOptionPane.YES_OPTION){
                            JOptionPane.showMessageDialog(this, "fr".equals(lang) ? "Récupérez votre reçu" : "Collect your receipt");
                    }
                    if(userType.equals("Guest")){
                        LoginPage l = new LoginPage(lang);
                        l.show();
                        dispose();
                    }else{
                        RegisteredUserMenu m=new RegisteredUserMenu(lang,r);
                        m.show();
                        dispose();
                    }
                    jButton1.setEnabled(true); // enable the submit button
                    ((Timer)e.getSource()).stop();
                });

                // start the timer to remove the loading dialog
                timer2.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CashPayment(lang,r,userType).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
