/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import java.awt.Font;
import static javaapplication2.PurchaseTicket.userTmp;
import javax.swing.JOptionPane;

/**
 *
 * @author rahul
 */
public class EditInfo extends javax.swing.JFrame {

    /**
     * Creates new form EditInfo
     */
    private static String lang;
    public static RegisteredUser userTmp;
    public EditInfo(String lang,RegisteredUser R) {
        userTmp=R;
        EditInfo.lang=lang;
        initComponents();
        setSize(1024, 803);
        getContentPane().setBackground(Color.WHITE);
         name.setText("fr".equals(lang)?"Nom ":"Name ");
        email.setText("fr".equals(lang)?"E-mail ":"Email ");
        address.setText("fr".equals(lang)?"Adresse ":"Address ");
        phonenum.setText("fr".equals(lang)?"Numéro de téléphone ":"Phone Number ");
        if ("fr".equals(EditInfo.lang)) {
            phonenum.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        }
        update.setText("fr".equals(lang)?"Mise à jour":"Update");
        jLabel1.setText(userTmp.getEmail());
        jTextField2.setText(userTmp.getName());
        jTextField3.setText(userTmp.getAddress());
        jTextField4.setText(userTmp.getPhoneNumber());
        jButton1.setText("fr".equals(lang)?"Retourner":"Go Back");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        phonenum = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        name.setForeground(new java.awt.Color(133, 220, 186));
        name.setText("Name");
        getContentPane().add(name);
        name.setBounds(130, 380, 260, 30);

        email.setBackground(new java.awt.Color(133, 220, 186));
        email.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        email.setForeground(new java.awt.Color(133, 220, 186));
        email.setText("Email Id");
        getContentPane().add(email);
        email.setBounds(130, 312, 230, 40);

        address.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        address.setForeground(new java.awt.Color(133, 220, 186));
        address.setText("Address");
        getContentPane().add(address);
        address.setBounds(130, 440, 260, 30);

        phonenum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        phonenum.setForeground(new java.awt.Color(133, 220, 186));
        phonenum.setText("Phone Num");
        getContentPane().add(phonenum);
        phonenum.setBounds(130, 500, 260, 30);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(390, 380, 260, 30);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(390, 440, 260, 30);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(390, 500, 260, 30);

        update.setBackground(new java.awt.Color(133, 220, 186));
        update.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(460, 610, 120, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/New Project (1) (1).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1030, 770);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 320, 300, 30);

        jButton1.setBackground(new java.awt.Color(133, 220, 186));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(810, 221, 150, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String emailID=userTmp.getEmail().trim();
        String name = jTextField2.getText().trim();
        String phonenum = jTextField4.getText().trim();
        String address = jTextField3.getText().trim();
        userTmp.setName(name);
        userTmp.setAddress(address);
        userTmp.setPhoneNumber(phonenum);
        if(RegisteredUser.updateUserInformationInUserDB(emailID, userTmp)){
            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Mise à jour réussie":"Update Successful");
            
        }
        else{
            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"mise à jour échouée":"Update Unsuccessful");
        }
        
        RegisteredUserMenu menu=new RegisteredUserMenu(lang,userTmp);
        menu.show();
        dispose();
        
    }//GEN-LAST:event_updateActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
            RegisteredUserMenu menu=new RegisteredUserMenu(lang,userTmp);
            menu.show();
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditInfo(lang,userTmp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phonenum;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
