/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import java.awt.Font;
/**
 *
 * @author rahul
 */
public class RegisteredUserMenu extends javax.swing.JFrame {

    /**
     * Creates new form RegisteredUserMenu
     */
    private static String lang;
    public static RegisteredUser userTmp;
    public RegisteredUserMenu(String Lang,RegisteredUser R) {
        RegisteredUserMenu.lang=Lang;
        userTmp=R;
        initComponents();
        setSize(1024, 803);
        getContentPane().setBackground(Color.WHITE);
        purchaseticket.setText("fr".equals(lang)?"Acheter un billet":"Purchase Ticket");
        editpersonal.setText("fr".equals(lang)?"Modifier les informations":"Edit Personal Info");
        if ("fr".equals(RegisteredUserMenu.lang)) {
            editpersonal.setFont(new Font("Segoe UI", Font.PLAIN, 20));
        }
         reload.setText("fr".equals(lang)?"Recharger IGo Carte":"Reload IGo Card");
         transcation.setText("fr".equals(lang)?"Historique des trans.":"Transcation History");
         if ("fr".equals(RegisteredUserMenu.lang)) {
            transcation.setFont(new Font("Segoe UI", Font.PLAIN, 19));
        }
         
         jButton1.setText("fr".equals(lang)?"Se déconnecter":"Logout");
         
         if ("fr".equals(RegisteredUserMenu.lang)) {
            jButton1.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseticket = new javax.swing.JButton();
        editpersonal = new javax.swing.JButton();
        reload = new javax.swing.JButton();
        transcation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        purchaseticket.setBackground(new java.awt.Color(133, 220, 186));
        purchaseticket.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        purchaseticket.setText("Purchase Ticket");
        purchaseticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseticketActionPerformed(evt);
            }
        });
        getContentPane().add(purchaseticket);
        purchaseticket.setBounds(220, 280, 290, 170);

        editpersonal.setBackground(new java.awt.Color(133, 220, 186));
        editpersonal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        editpersonal.setText("Edit Personal Info");
        editpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpersonalActionPerformed(evt);
            }
        });
        getContentPane().add(editpersonal);
        editpersonal.setBounds(220, 490, 290, 160);

        reload.setBackground(new java.awt.Color(133, 220, 186));
        reload.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        reload.setText("Reload IGo Card");
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        getContentPane().add(reload);
        reload.setBounds(560, 280, 250, 170);

        transcation.setBackground(new java.awt.Color(133, 220, 186));
        transcation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transcation.setText("Transcation History");
        transcation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transcationActionPerformed(evt);
            }
        });
        getContentPane().add(transcation);
        transcation.setBounds(560, 490, 250, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/New Project (1) (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 770);

        jButton1.setBackground(new java.awt.Color(133, 220, 186));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(860, 230, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseticketActionPerformed
        // TODO add your handling code here:
        PurchaseTicket t = new PurchaseTicket(lang,this.userTmp,"RegisteredUser");
            t.show();
            dispose();
    }//GEN-LAST:event_purchaseticketActionPerformed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        // TODO add your handling code here:
        ReloadIGoMenu reload = new ReloadIGoMenu(lang,this.userTmp);
            reload.show();
            dispose();
    }//GEN-LAST:event_reloadActionPerformed

    private void editpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpersonalActionPerformed
        // TODO add your handling code here:
        EditInfo edit=new EditInfo(lang,this.userTmp);
        edit.show();
        dispose();
        
    }//GEN-LAST:event_editpersonalActionPerformed

    private void transcationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transcationActionPerformed
        // TODO add your handling code here:
        String userEmail = userTmp.getEmail().trim();
        TranscationHistory th = new TranscationHistory(lang,userTmp,RechargeIGoCardInformation.retrieveInformationFromRechargeIGoCardDB(userEmail),PurchaseTicketInformation.retrieveInformationFromPurchaseTicketDB(userEmail));
        th.show();
        dispose();
    }//GEN-LAST:event_transcationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            LanguageSelection Lan=new LanguageSelection();
            Lan.show();
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisteredUserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisteredUserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisteredUserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisteredUserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisteredUserMenu(lang,userTmp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editpersonal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton purchaseticket;
    private javax.swing.JButton reload;
    private javax.swing.JButton transcation;
    // End of variables declaration//GEN-END:variables
}
