/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import static javaapplication2.PurchaseTicket.userTmp;
import javax.swing.JOptionPane;

/**
 *
 * @author rahul
 */
public class ReloadIGoMenu extends javax.swing.JFrame {

    /**
     * Creates new form ReloadIGoMenu
     */
    public static RegisteredUser userTmp;
    private static String lang;
    public ReloadIGoMenu(String lang,RegisteredUser R) {
        userTmp=R;
        ReloadIGoMenu.lang=lang;
        initComponents();
        setSize(1024, 803);
        getContentPane().setBackground(Color.WHITE);
        weekly.setText("fr".equals(lang)?"Laissez-passer hebdomadaire-$30":"Weekly Pass-$30");
        monthly.setText("fr".equals(lang)?"Laissez-passer mensuel-$90":"Monthly Pass-$90");
        sudent.setText("fr".equals(lang)?"Laissez-passer étudiant/aîné mensuel-$54":"Student/Elder Pass Monthly-$54");
        cash.setText("fr".equals(lang)?"Espèces":"Cash");
        card.setText("fr".equals(lang)?"Carte":"Card");
        quater.setText("fr".equals(lang)?"Et quart-$190":"Quater Pass-$190");
        annual.setText("fr".equals(lang)?"Annuelle-$650":"Annual Pass-$650");
        payvia.setText("fr".equals(lang)?"Payer via":"Pay Via");
        gobackbutton.setText("fr".equals(lang)?"Retourner":"Go Back");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        weekly = new javax.swing.JRadioButton();
        monthly = new javax.swing.JRadioButton();
        sudent = new javax.swing.JRadioButton();
        payvia = new javax.swing.JLabel();
        card = new javax.swing.JButton();
        cash = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gobackbutton = new javax.swing.JButton();
        quater = new javax.swing.JRadioButton();
        annual = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        weekly.setBackground(new java.awt.Color(133, 220, 186));
        buttonGroup1.add(weekly);
        weekly.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        weekly.setText("Weekly Pass- $25");
        weekly.setMaximumSize(new java.awt.Dimension(291, 53));
        weekly.setMinimumSize(new java.awt.Dimension(291, 53));
        weekly.setOpaque(true);
        getContentPane().add(weekly);
        weekly.setBounds(190, 270, 340, 50);

        monthly.setBackground(new java.awt.Color(133, 220, 186));
        buttonGroup1.add(monthly);
        monthly.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        monthly.setText("Montly Pass- $ 90");
        monthly.setOpaque(true);
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });
        getContentPane().add(monthly);
        monthly.setBounds(190, 330, 330, 40);

        sudent.setBackground(new java.awt.Color(133, 220, 186));
        buttonGroup1.add(sudent);
        sudent.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sudent.setText("Student/Elder Pass Monthly -$54");
        sudent.setOpaque(true);
        sudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sudentActionPerformed(evt);
            }
        });
        getContentPane().add(sudent);
        sudent.setBounds(190, 500, 560, 50);

        payvia.setBackground(new java.awt.Color(133, 220, 186));
        payvia.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        payvia.setForeground(new java.awt.Color(133, 220, 186));
        payvia.setText("Pay Via:");
        getContentPane().add(payvia);
        payvia.setBounds(190, 590, 220, 60);

        card.setBackground(new java.awt.Color(133, 220, 186));
        card.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        card.setText("Card");
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });
        getContentPane().add(card);
        card.setBounds(410, 590, 160, 60);

        cash.setBackground(new java.awt.Color(133, 220, 186));
        cash.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        getContentPane().add(cash);
        cash.setBounds(620, 590, 160, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/New Project (1) (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, -50, 1010, 880);

        gobackbutton.setBackground(new java.awt.Color(133, 220, 186));
        gobackbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gobackbutton.setText("Go Back");
        gobackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(gobackbutton);
        gobackbutton.setBounds(830, 220, 130, 60);

        quater.setBackground(new java.awt.Color(133, 220, 186));
        buttonGroup1.add(quater);
        quater.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        quater.setText("Quarter Pass- $ 190");
        quater.setOpaque(true);
        getContentPane().add(quater);
        quater.setBounds(190, 380, 340, 50);

        annual.setBackground(new java.awt.Color(133, 220, 186));
        buttonGroup1.add(annual);
        annual.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        annual.setText("Annual Pass-$650");
        annual.setOpaque(true);
        getContentPane().add(annual);
        annual.setBounds(190, 440, 320, 52);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sudentActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
        String tripType=null;
        double amount=0;
        String usertype=userTmp.getUserType().trim();
        if(sudent.isSelected()){
            if(usertype.equals("Student/Senior")){
                tripType="Student/Senior Pass Monthly";
            amount=54;
            }
            else{
                JOptionPane.showMessageDialog(this, "fr".equals(lang) ? "Vous n'êtes pas autorisé" : "You are not Allowed");
                sudent.setSelected(false);
                monthly.setSelected(false);
                 weekly.setSelected(false);
                  annual.setSelected(false);
                  quater.setSelected(false);
                 return;
            }
        }
        else if(weekly.isSelected()){
            tripType="Weekly Pass";
            amount=25;
        }
        else if(monthly.isSelected()){
            tripType="Monthly Pass";
            amount=90;
        }
        else if(annual.isSelected()){
            tripType="Annual Pass";
            amount=650;
        }
        else if(quater.isSelected()){
            tripType="Quater Pass";
            amount=190;
        }
        else{
            return;
        }
        boolean ticketBooked; 
        RechargeIGoCardInformation ticketInfo=new RechargeIGoCardInformation(userTmp.getEmail(),tripType,amount,userTmp.getPhoneNumber(),"Cash");
        ticketBooked=RechargeIGoCardInformation.writeIntoRechargeIGoCardDB(ticketInfo);
        if(ticketBooked){
            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Billet réservé avec succès":"Recharge IGo Successfully");
            sudent.setSelected(false);
             monthly.setSelected(false);
              weekly.setSelected(false);
              quater.setSelected(false);
                annual.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Erreur : Échec":"Error: Unsuccessfull");
            weekly.setSelected(false);
             monthly.setSelected(false);
              sudent.setSelected(false);
              quater.setSelected(false);
                 annual.setSelected(false);
        }
    }//GEN-LAST:event_cashActionPerformed

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthlyActionPerformed

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        // TODO add your handling code here:
        String tripType=null;
        double amount=0;
        String usertype=userTmp.getUserType().trim();
        if(sudent.isSelected()){
            if(usertype.equals("Student/Senior")){
                tripType="Student/Senior Pass Monthly";
            amount=54;
            }
            else{
                JOptionPane.showMessageDialog(this, "fr".equals(lang) ? "Vous n'êtes pas autorisé" : "You are not Allowed");
                sudent.setSelected(false);
                monthly.setSelected(false);
                 weekly.setSelected(false);
                 quater.setSelected(false);
                 annual.setSelected(false);
                 return;
            }
        }
        else if(weekly.isSelected()){
            tripType="Weekly Pass";
            amount=25;
        }
        else if(monthly.isSelected()){
            tripType="Monthly Pass";
            amount=90;
        }
        else if(annual.isSelected()){
            tripType="Annual Pass";
            amount=650;
        }
        else if(quater.isSelected()){
            tripType="Quater Pass";
            amount=190;
        }
        else{
            return;
        }
        boolean ticketBooked; 
        RechargeIGoCardInformation ticketInfo=new RechargeIGoCardInformation(userTmp.getEmail(),tripType,amount,userTmp.getPhoneNumber(),"Card");
        ticketBooked=RechargeIGoCardInformation.writeIntoRechargeIGoCardDB(ticketInfo);
        if(ticketBooked){
            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Billet réservé avec succès":"Recharge IGo Successfully");
            sudent.setSelected(false);
             monthly.setSelected(false);
              weekly.setSelected(false);
              quater.setSelected(false);
                 annual.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "fr".equals(lang)?"Erreur : Échec":"Error: Unsuccessfull");
            weekly.setSelected(false);
             monthly.setSelected(false);
              sudent.setSelected(false);
              quater.setSelected(false);
                 annual.setSelected(false);
        }
    }//GEN-LAST:event_cardActionPerformed

    private void gobackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackbuttonActionPerformed
        // TODO add your handling code here:
        RegisteredUserMenu m=new RegisteredUserMenu(lang,userTmp);
                m.show();
                dispose();
    }//GEN-LAST:event_gobackbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReloadIGoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReloadIGoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReloadIGoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReloadIGoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReloadIGoMenu(lang,userTmp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton annual;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton card;
    private javax.swing.JButton cash;
    private javax.swing.JButton gobackbutton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton monthly;
    private javax.swing.JLabel payvia;
    private javax.swing.JRadioButton quater;
    private javax.swing.JRadioButton sudent;
    private javax.swing.JRadioButton weekly;
    // End of variables declaration//GEN-END:variables
}
